[package]
name = "mida-core"
version.workspace = true
edition.workspace = true
description = "Debugger core: process creation, breakpoints, debug event loop"
repository.workspace = true
license.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
pelite = { workspace = true }
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
thiserror = { workspace = true }
tracing = { workspace = true }
windows = { workspace = true }

[dev-dependencies]
serde_json = "1"
